//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GanttCrudSql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GanttData
    {
        public string TaskId { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Duration { get; set; }
        public string Progress { get; set; }
        public string ParentId { get; set; }
        public string Predecessor { get; set; }
    }
}
